from secure_secrets_module import *
secmod = secrets()
secmod.add_secret('example','Hello World')
print(secmod.get_secret('example'))
secmod.add_secret('example2',['Hello','World',2])
print(secmod.get_secret('example2'))
secmod.add_secret('example3',b'534')
print(secmod.get_secret('example3'),type(secmod.get_secret('example3')))
#print(secmod.get_secret('Key_AES'))
#secmod.password_change()